config/routes.rb
Rails.application.routes.draw do
  resources :todos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  def index
  	@todo = Todo.all
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.save
    redirect_to todo_path(@todo)
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])
    @todo.update(todo_params)
    redirect_to todo_path(@todo)
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    redirect_to todos_path
  end

  private

  def todo_params
    params.require(:todo).permit(:name, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_for(@todo) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.submit %>
<% end %>
<br></br>
<%= link_to "Home", todos_path %>

app/views/todos/edit.html.erb
<%= render 'form' %>

app/views/todos/index.html.erb
<% @todo.each do |todo| %>
  <h2><%= todo.name %></h2>
  <p><%= todo.description %></p>
  <br></br>
  <%= link_to "Show", todo_path(todo.id) %>
  <%= link_to "New", new_todo_path(todo.id) %>
  <%= link_to "Edit", edit_todo_path(todo.id) %>
  <%= link_to "Delete", todo_path(todo.id),
      method: :delete,
      data: { confirm: "Are you sure?" } %>
<% end %>

app/views/todos/new.html.erb
<%= render 'form' %>

app/views/todos/show.html.erb
<h2><%= @todo.name %></h2>
<p><%= @todo.description %></p>

<%= link_to "Home", todos_path %>